language: php
php:
- 7.3
sudo: true
cache:
  directories:
  - "$HOME/.composer/cache"
notifications:
  email:
    recipients:
    - info@failx.de
    on_success: change
    on_failure: change
before_script:
- composer global require -q --dev deployer/deployer:~6.4 deployphp/recipes:~6.2
script:
- "/home/php/.composer/vendor/bin/dep -f./.deployer/config.php deploy prod"
#before_install:
#- openssl aes-256-cbc -K $encrypted_65531ac48767_key -iv $encrypted_65531ac48767_iv
  #-in deploy_rsa.enc -out deploy_rsa -d

addons:
  ssh_known_hosts: oc-vm39.riconnect.de

before_deploy:
  - openssl aes-256-cbc -K $encrypted_65531ac48767_key -iv $encrypted_65531ac48767_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
